id: I80EDEC10
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:03:24.285483+00:00
last_modified: 2022-12-14 18:03:24.285506+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-061-006
  title: Toh_186-The_Teaching_on_the_Extraordinary_Transformation-v2
bases:
  '4334':
    source_metadata: null
    order: 1
    base_file: 4334.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
